### PR TITLE
Bring your doc-master up to speed with TKL Odoo Master

### PR DESCRIPTION
**Pull request by DocCyblade**
Jed has been keeping my master up to date. This PR will bring your doc-master in-line with TKL

### CODE REVIEW

**Comment by l-arnold** [comment]
Ok,  I need to get mine up to date as well, following Ken's lead.

**Comment by DocCyblade** [comment]
:-) Getting back in the saddle... Work had been the worst it's ever been. I have a month where I'll be able to throw in some time :-)

**Comment by l-arnold** [comment]
Updated.  Thanks for that Ken.  I was computerless and not seeing on my phone the detail.

**Comment by l-arnold** [comment]
I think we should consider building Ether-Pad onto the Odoo Server.  Strange they expect a separate server for it.  Here is some info on how to install.

http://www.emiprotechnologies.com/technical_notes/odoo-technical-notes-59/post/install-configure-and-setting-up-etherpad-server-for-odoo-253

**Comment by JedMeister** [comment]
We have Etherpad server already (see [here](https://www.turnkeylinux.org/etherpad)). IMO adding additional software such as this (which that may not be needed by many users) to the Odoo image is not ideal. 

Considering that Odoo is already fairly system intensive (nowhere near as resource hungry as some others but still up there...) I think adding software that adds significant resource overhead is a bad plan.

Having said that, if you can convince me that a significant majority of users would find it useful/valuable then maybe we could do it...

**Comment by l-arnold** [comment]
It comes down to being able to document what a Project (and other primary subject) is about.
I see this relatively similar to the work we put in getting Printing to work properly (did not out of the box)

Seems CRAZY to have to run a separate server just to  edit some Text.  According to the citation above the "installation on any server is easy:
- sudo su - etherpad -s /bin/bash 
- mkdir -p ~/local/etherpad

## \- cd ~/local/etherpad

## \- git clone git://github.com/ether/etherpad-lite.git
- cd etherpad-lite
- bin/run.sh

Compare these two images in the description field)

screenshot 2016-03-10 17 22 48

ir_attachment_11706

**Comment by JedMeister** [comment]
Ok you've convinced me! :smile: 

I just had a quick look and if you do a shallow clone (i.e. `--depth 1`) then it's only about 1MB. I would suggest that it might be better to use the latest release tag, rather than just getting the latest dev. I.e.:

```
git clone --branch 1.5.7 --depth 1 https://github.com/ether/etherpad-lite.git
```

You can find what the latest release version is here: https://github.com/ether/etherpad-lite/releases

Also IMO it shoudl be installed to /opt (instead of ~) and should probably just run under the same user as Odoo (IIRC that was just `odoo` but I might be wrong. Also to make it more robust and so that it auto starts it should probably be set up as a daemon... FWIW they have documented a systemD and sysvinit service files here: https://github.com/ether/etherpad-lite/wiki/How-to-deploy-Etherpad-Lite-as-a-service

**Comment by l-arnold** [comment]
I see your post now.  I just went and checked off this setting, but really just made it so there is NO Description box at all (though there is a Tab for Description still..
- [ ] Use integrated collaborative note pads on task
  
  We need to see if we can run it on LocalHost and have the Setup somehow be Preconfigured at Setup.  Seems to me anyway.

**Comment by l-arnold** [comment]
Does it make sense just to use the "app component install" in the EtherPad App so that whatever is updated there is updated to Odoo (generally).
Back when I was playing w/ including Samba it seemed to be working that way.

**Comment by JedMeister** [comment]
Actually it looks like you need to use the development version (i.e. don't use the `--branch 1.5.7` for now...) The release is a little old and it seems there is a Debian related bug...

Also I found some Debian install instructions:
https://github.com/ether/etherpad-lite#gnulinux-and-other-unix-like-systems

**Comment by JedMeister** [comment]
Sorry I don't understand what you mean. If you don't use the `--branch` flag then it will download the latest version.

**Comment by DocCyblade** [comment]
Good stuff ;-)

@l-arnold open a issue to see if we can play around and add that to the setup :-) looks pretty straight forward

**Comment by l-arnold** [comment]
where should I open the issue?  (tracker? )  Seems like it.

**Comment by l-arnold** [comment]
I meant to use the build on ether-pad lite so that TKLDEV just takes what is built there.  Sounds like we need a specific build that is likely different than the TKL-Etherpad  (need to check)

Early version of Odoo from Carlos was throwing Samba in out of the TKL Repository builds.  Need to look how it was done, but pretty much how webmin etc are added via TKLDEV.

**Comment by l-arnold** [comment]
(IE should the "issue" be in this repo, ken's repo, or tkl/tracker ?

**Comment by DocCyblade** [comment]
@JedMeister what say you regarding where the issue (feature request)

**Comment by l-arnold** [comment]
Happy to move it.  I just threw an issue in here anyway but might be better in the TKL world and you guys just coach me through keeping this repo up to date.

Out of practice again.

**Comment by JedMeister** [comment]
@DocCyblade - I'm happy for this to go on the TurnKey tracker, in fact it probably should be IMO.

**Pull request merged**
