### PR TITLE
Merge to dev

### PR DESCRIPTION
**Pull request by DocCyblade**
Keep this open until I have a chance to test a few times. Creating here so we can dialog about it in the PR if needed.

### CODE REVIEW

**Comment by DocCyblade** [comment]
My first test failed... i think because i did not update my common. trying again

**Comment by l-arnold** [comment]
Are you testing in dev-wip1 or dev with proposed merges.

**Comment by DocCyblade** [comment]
@l-arnold  - dev-wip1

**Comment by DocCyblade** [comment]
Issue was my common was out of date. Running installer now

**Comment by DocCyblade** [comment]
this looks good.

**Comment by l-arnold** [comment]
Ok.  Does it matter who merges?  Go for it if its open still.  Otherwise I will in 10-15 min.  Thanks for the check up.

**Pull request merged**
