### PR TITLE
Basic change in index.php

### PR DESCRIPTION
**Pull request by l-arnold**
Learning if Pull Requests are two directional  

IE, I changed "dev" branch rather than "dev-wip1" branch

Now pulling from base(dev-wip1) to compare (dev).
Might go from dev to dev-1  and might not.

### CODE REVIEW

**Comment by l-arnold** [comment]
Is this something we should merge or should we close it?  I mistakenly committed to dev and wanted to send it "down branch" to dev-wip1

Since it was 1 "non hyper critical file" (webconsole) I also "reversed" what I would logically set up in the Pull trying to find out what the impact would be.  (I can see it would merge into dev-wip1 from dev up above, so all looks good)

**Comment by l-arnold** [comment]
Performed the merge.  More work to do.  Will "stay" in dev-wip1.  Really will.  (whish I could make a "personal default" the way a shell session does.  Web system always defaults to "default" whatevever is set so you need o check it frequently.

**Comment by JedMeister** [comment]
If you `git checkout <branch-name>` then it will stay on that branch (until you change it).

There is also a way to make the bash prompt show what branch you are on. I have been meaning to have a play with that for a while now as I think it would be a handy default on TKLDev...

**Comment by l-arnold** [comment]
'"git branch"  should tell you which one you are in in shell (bash prompt?)

Will ne working later today on some of this.

**Comment by JedMeister** [comment]
Also FWIW if you commit to the wrong branch you can do the following; this assumes that you have a single commit which you committed to the wrong branch, want to move it to another branch and remove it from the accidental branch. 

```
git checkout <branch-you-meant-to-commit-to>
git cherry-pick <commit-id>
git checkout <branch-you-accidentally-committed-to>
git reset --hard HEAD~1
```

**Comment by JedMeister** [comment]
Yes `git branch` will display all local branches with an asterisk ('*') next to the one checked out. `git branch -a` will show all branches (local and remote).

**Pull request merged**
