### PR TITLE
Help Needed (says won't go Automatically)

### PR DESCRIPTION
**Pull request by l-arnold**
Trying to take SAMBA out.  Was trying to avoid this conflict but seems to have stayed in place.

Thoughts on how to Fix?

### CODE REVIEW

**Comment by l-arnold** [comment]
Made the mistake of modifying one file in Dev, but I did not think it was also changed in dev-wip1

Statusof dev-wip1 says: This branch is 3 commits ahead, 5 commits behind dev.

**Comment by l-arnold** [comment]
Not clear as to the problem really:  This outlines the changes I was trying to make:
https://github.com/l-arnold/tkl-nomadic-odoo/compare/dev-wip1

**Comment by JedMeister** [comment]
I can take a look quickly if you want. First I need some clarity around your dev flow. 

So is your "dev" branch the main development branch? Sort of a bit like "master" is currently on the TKL git repos? And "dev-wpi1" is like your personal current working branch? So if I were to do a build test which branch should I be testing/building? If I want to tweak something should I do a PR against the "dev" branch or your "dev-wip1" branch?

Actually I've just re-read this thread and while I get the overarching aim is to remove Samba I'm not totally clear on what you are doing here? You link to a comparison of dev against dev-wip1 so are you working in dev and want to merge it with dev-wpi1? Sorry I feel like I am missing something...

**Comment by l-arnold** [comment]
Dev is functional Master.
dev-wip1 is where I am supposed to be working

ken has been working in
kens-dev-wip1  which would flow to dev-wip1

ideally you would make a branch
jeds-dev-wip1  (and I would make a lans-dev-wip1)

We will flow from Dev to Master when we have a real RC.

Make Sense?

**Comment by l-arnold** [comment]
To Answer where we want it really to PR though, is 

We want it to the Dev branch as I was trying to do with that PR.  (prob was I had made a change in github.com (web) in that branch rather than dev-wip1

**Comment by JedMeister** [comment]
Ok cool thanks.

TBH I'd love to help out. I am currently working on domain controller - it's the last app that needs updating and TBH Samba4 is a complex beast that has been doing my head in... 

I'll get to it ASAP but it will later today; a few hours at the soonest...

**Comment by JedMeister** [comment]
I'm about to do a PR to your "dev-wp1" branch to fix your merge conflict but here is step-by-step how I did it...

```
root@tkldev products/landis-odoo# git checkout dev-wip1 
Switched to branch 'dev-wip1'
Your branch is up-to-date with 'landis/dev-wip1'.

root@tkldev products/landis-odoo# git merge dev
Auto-merging Makefile
CONFLICT (content): Merge conflict in Makefile
Automatic merge failed; fix conflicts and then commit the result.
```

So I opened Makefile (I use vim but any editor should be fine)

```
root@tkldev products/landis-odoo# vim Makefile
```

And this is what I see in Makefile:

```
<<<<<<< HEAD
=======
COMMON_OVERLAYS = tkl-webcp samba-fileserver samba-sid-inithook
COMMON_CONF = tkl-webcp fileserver-storage samba-rootpass samba-webmin

>>>>>>> dev
CREDIT_ANCHORTEXT = Turnkey Odoo Appliance

include $(FAB_PATH)/common/mk/turnkey/lapp.mk
include $(FAB_PATH)/common/mk/turnkey.m
```

So it's pretty easy to see what is happening here. I just removed the conflicted stuff so it now looks like this:

```
CREDIT_ANCHORTEXT = Turnkey Odoo Appliance

include $(FAB_PATH)/common/mk/turnkey/lapp.mk
include $(FAB_PATH)/common/mk/turnkey.mk
```

I then commit all changes (`-a` switch) and add a message (`-m` switch) using the shorthand alias (`gc` instead of `git commit`) that is configured by default in TKLDev:

```
root@tkldev products/landis-odoo# gc -am "fixed conflict and merged"
[dev-wip1 ef31544] fixed conflict and merged
```

Now I just realised I probably should have been doing this in my own branch (rather than yours) then issued a PR. Seeing as I've just been working in my local repo; the easiest thing is to just create the new branch from "dev-wip1" and delete (and recreate) my local "dev-wip1". (the `-b` switch with checkout makes a new branch; the `-t` switch sets the branch to track a specific remote branch)

```
root@tkldev products/landis-odoo# git checkout -b jed-dev-wip
Switched to a new branch 'jed-dev-wip'
root@tkldev products/landis-odoo# git push origin jed-dev-wip 
Total 0 (delta 0), reused 0 (delta 0)
To git@github.com:JedMeister/landis-odoo.git
 * [new branch]      jed-dev-wip -> jed-dev-wip
root@tkldev products/landis-odoo# git branch -D dev-wip1 
Deleted branch dev-wip1 (was ef31544).
root@tkldev products/landis-odoo# git checkout -b landis-dev-wip -t landis/dev-wip1 
Branch landis-dev-wip set up to track remote branch dev-wip1 from landis.
Switched to a new branch 'landis-dev-wip'
```

Now I just need to do a PR (in GitHub) against your "dev-wip1`" branch and we'll be good to go! :smile:

**Comment by JedMeister** [comment]
Have a look at the fixed PR (#29) and merge at your convenience. OTOH if you want to do it yourself (and just close my PR) then go for it! :smile: Hopefully my (very verbose) explanation of what I did (above) is of value and you'll be able to fix it yourself really easy! Obviously you don't need to do everything that I did because it's your repo...!

**Comment by l-arnold** [comment]
Thanks Jeremy.  I see the 2 lines added.  Will run with your PR.  Likely I should just close my PR.  Will see.

**Comment by l-arnold** [comment]
So the new PR pulled them together.  Interesteing.  Only one merge command.

**Pull request merged**
