### PR TITLE
Balancing Merge.  May not be required.

### PR DESCRIPTION
**Pull request by l-arnold**
Dev wip1 - samba removal - some documentation updates

### CODE REVIEW

**Comment by JedMeister** [comment]
Looks like this didn't actually change anything... "Showing ￼ 0 changed files  with 0 additions and 0 deletions."

**Comment by l-arnold** [comment]
I know.  I was reasponding to the "xyz" branch is 1 commit in front of the "other" branch.  I thought they should be the same.  Evidently the Pull Request is a commit thus the inbalance.

**Comment by JedMeister** [comment]
Ok so let's imagine the 2 branches are 'master' and 'dev'. You work away in 'dev' committing as you go. When everything is awesome you merge 'dev' into 'master'.

When you merge 'dev' into 'master' it pulls in the complete 'dev' git history (each of the commits you did in 'dev' is still listed separately in 'master') but the merge creates a new commit object (which is essentially empty but contains the note of the branch/fork which was merged). This will make 'master' one commit ahead of dev, although the code will actually be the same! :smile:

**Comment by l-arnold** [comment]
:+1:

**Pull request merged**
