### PR TITLE
V14.2 update

### PR DESCRIPTION
**Pull request by DocCyblade**
Updated for v14.2

### CODE REVIEW

**Comment by JedMeister** [comment]
I think you meant to lodge this PR against the [TurnKey fork](https://github.com/turnkeylinux-apps/odoo)?! 

Doesn't matter though, because I've done it! :+1: See https://github.com/turnkeylinux-apps/odoo/pull/7

**Comment by l-arnold** [comment]
I think Ken was very nicely keeping this in synch! Thank you ken.  I will merge in the AM.

I need to fire up my TKLDEV.server and give 14.2 a spin.

Looking forward
Thank you,

Landis

**Comment by JedMeister** [comment]
I reckon you're right @l-arnold but I'm pretty sure he also meant to open a PR against the main TurnKey repo too.

FWIW, in case you weren't already aware, we have decided to just stick with a single Odoo v8 appliance for v14.2. So this shouldn't be much different to the v14.1 appliance (just latest release of Odoo v8).

Once we've finished v14.2, then we'll start work on TurnKey v15.0 (based on Debian Stretch/9). For v15.0, we'll probably still only have one Odoo appliance, but almost certainly Odoo v10.

**Comment by DocCyblade** [comment]
Sorry about that, I forgot my copy is a fork of @l-arnold. Was a bit click happy

**Comment by DocCyblade** [comment]
@JedMeister thanks for pulling it into the correct repo!

**Comment by l-arnold** [comment]
So..  here we are.  Tkl-Odoo is at 16.1 now about to move to 17.x

how do I progressively move my repo forward through those generations?  Wanting to be able to work in current then also build some branches so that I can line up with some of the Odoo branch structures.

I'd also like to provide a choice to the user about using a Git install and folder structure, or a debian repo install and folder structure.

Sorry to be a not know what I feel I should know by now about Git.

**Pull request merged**
